# Python module providing a high-level interface to the KCWI instrument.

override SYSNAM = kss/kcwi/scripts/python/Keck1ConfManager/static
override VERNUM = 1.0

DIRS = fonts js css

################################################################################
# KROOT boilerplate:
# Include general make rules, using default values for the key environment
# variables if they are not already set.

ifndef KROOT
	KROOT = /kroot
endif

ifndef RELNAM
	RELNAM = default
endif

ifndef RELDIR
	RELDIR = $(KROOT)/rel/$(RELNAM)
endif

include $(KROOT)/etc/config.mk
################################################################################
